databases:
  - name: HAWAII_DB
    databaseName: hawaii_db
    user: HAWAII
    region: singapore

services:
  - type: web
    name: HAWAII
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HAWAII_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

